rules:
  - trigger: BLOCK_PLACE
    target: DIAMOND_BLOCK
    effects:
      - type: FLAME
        amount: 50
        speed: 0.05
        offset:
          x: 0.5
          y: 0.5
          z: 0.5

  # Комбо-эффекты. можно добавлять неограниченное кол-во типов эффектов на 1 ивент (тригер)
  - trigger: CRAFT_ITEM
    target: CRAFTING_TABLE
    effects:
      - type: FLAME
        amount: 50
        speed: 0.05
        offset:
          x: 0.5
          y: 0.5
          z: 0.5

      - type: FIREWORK
        shape: STAR
        flicker: true
        trail: true
        power: 1
        colors:
          - "FFD700"
          - "FFFFFF"

      - type: TITLE
        title: "<gradient:gold:yellow>Первый верстак!</gradient>"
        subtitle: "<white>Начало великого пути</white>"
        fadeIn: 20
        stay: 60
        fadeOut: 20
