site_name: VillVisuals WIKI
site_url: https://LIONVILL.github.io/VillVisual/
site_description: Документация по триггерам и эффектам
site_author: Villoni
repo_name: LIONVILL/VillVisual
repo_url: https://github.com/LIONVILL/VillVisual

theme:
  name: material
  language: ru
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Тёмная тема
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Светлая тема
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
    - toc.follow
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

plugins:
  - search

nav:
  - Главная: index.md
  - Гайды:
      - Триггеры: guides/triggers.md
      - Таргеты: guides/targets.md
      - Эффекты: guides/effects.md
